### PR TITLE
Save results to NWB

### PR DESCRIPTION
**Pull request by luiztauffer**
TODO:
- [ ] After merging #46, change the uploaded file to be the NWB file.
- [ ] Allow NWB output only if input was NWB, extract metadata from input file

Saves segmentation results to a NWB file. 

References:
- https://pynwb.readthedocs.io/en/latest/tutorials/domain/ophys.html#plane-segmentation
- https://pynwb.readthedocs.io/en/latest/pynwb.ophys.html#

### CODE REVIEW

**Comment by luiztauffer** [comment]
NWB files allow for rich metadata (experimental setup, subject information, recording settings, etc...) which is very important when data is shared, e.g. in public repositories such as dandi archive. When voluseg saves its output to a NWB file, it could populate the metadata in two possible ways:
- copy most of it from an input file, if that input file was NWB
- accept a metadata dictionary as an optional parameter in the parameters dictionary

thoughts on this, @mikarubi ?

**Comment by luiztauffer** [comment]
@mikarubi 
With NWB we have the opportunity to standardize the output of voluseg in a way that’s straightforward for the users to interpret and analyze. Here are the points we need to decide in order to finish this feature:

## Output format
How should voluseg save its results?
- Keep only the current h5 format, do not output as NWB
- Keep the current h5 format, optionally output as NWB as well (can be run as a post-pipeline step)
- Choose between h5 or NWB output format (pre-pipeline run)
- Output only as NWB

## NWB metadata
NWB files allow for rich metadata (experimental setup, subject information, recording settings, etc...) which is very important when data is shared, e.g. in public repositories such as dandi archive. When voluseg saves its output to a NWB file, it could populate the metadata in two possible ways:

- copy most of it from an input file, if that input file was NWB
- accept a metadata dictionary as an optional parameter in the parameters dictionary, this would be necessary if the input data does not come from NWB

**Comment by mikarubi** [comment]
I think it would be best to save nwb inputs as nwb (and keep all the nwb metadata), and save all other formats as hdf5 (and NOT give users the option to choose the type of output).

In order to incorporate NWB:
1. We need to include the nwb extension here, https://github.com/mikarubi/voluseg/blob/master/voluseg/_tools/save_volume.py
2. We also need to generalize the following code: https://github.com/mikarubi/voluseg/blob/4b998544f933e0903ff16f47983d7f86c20f6803/voluseg/_steps/step4b.py#L85-L88
Here, my suggestion is to move this code to a new function called `load_timeseries`, and then treat nwb vs hdf5 separately within the function.

Regarding the metadata, I guess some users may want to convert a generic hdf5 output to nwb. This seems like a very general task that could probably be dealt with separately (e.g. after segmentation or even independently of voluseg?)

**Comment by luiztauffer** [comment]
I don't think there's much advantage in converting to NWB in intermediate steps, so we wouldn't have to touch `save_volume` and `step4` at all.
My thinking is that the final segmentation results, the clean cells, should go in NWB, since it has the proper metadata and structure to organize the segmentation results better than the current arbitrary h5 fields.

**Comment by mikarubi** [comment]
Ok, got it. So then we can keep the intermediate h5 structure, and convert into nwb at the very end. I agree with this plan.

**Comment by luiztauffer** [comment]
@mikarubi I'll go ahead and merge this, because the changes required to solve [this docs problem](https://github.com/mikarubi/voluseg/pull/48#issuecomment-2446391583) will most likely create annoying conflicts later on.
I will open issues related to the points left to be resolved here

**Pull request merged**
